version: "3"

services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
    volumes:
      - data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  data:
